# Generated by Django 4.0.5 on 2022-06-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('min_cust', models.IntegerField()),
                ('max_cust', models.IntegerField()),
                ('avg_cookies', models.IntegerField()),
            ],
        ),
    ]
